name: Build and Deploy to Coolify

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: yousefshawkyetg/bbb-application-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Coolify
        if: github.ref == 'refs/heads/main'
        uses: gitnasr/coolify-trigger-deploy@v2.0.0
        with:
          docker_image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          coolify_url: ${{ secrets.COOLIFY_URL }}
          coolify_resource_id: ${{ secrets.COOLIFY_RESOURCE_ID }}
          coolify_api_token: ${{ secrets.COOLIFY_API_TOKEN }}
